# Generated by Django 4.2.4 on 2023-08-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
